filter:
    excluded_paths:
        - libs/*
        - resources/*
        - vendor/*
checks:
    php:
        code_rating: true
        duplication: true
        fix_php_opening_tag: false
        remove_php_closing_tag: false
        one_class_per_file: true
        side_effects_or_types: false
        no_mixed_inline_html: false
        require_braces_around_control_structures: false
        php5_style_constructor: true
        no_global_keyword: false
        avoid_usage_of_logical_operators: true
        psr2_class_declaration: false
        no_underscore_prefix_in_properties: true
        no_underscore_prefix_in_methods: true
        blank_line_after_namespace_declaration: true
        single_namespace_per_use: false
        psr2_switch_declaration: false
        psr2_control_structure_declaration: false
        avoid_superglobals: false
        security_vulnerabilities: false
        no_exit: false
        properties_in_camelcaps: true
        no_short_variable_names:
            minimum: '3'
        optional_parameters_at_the_end: true
        param_doc_comment_if_not_inferrable: true
        no_short_method_names:
            minimum: ''
        newline_at_end_of_file: true
        function_in_camel_caps: true
        encourage_single_quotes: true
        encourage_postdec_operator: true
        classes_in_camel_caps: true
        avoid_perl_style_comments: true
        avoid_multiple_statements_on_same_line: true
        avoid_closing_tag: false

coding_style:
    php:
        indentation:
            general:
                use_tabs: true
        braces:
            classes_functions:
                class: new-line
                function: new-line
                closure: end-of-line
            for:
                opening: end-of-line
            while:
                opening: end-of-line
            do_while:
                opening: end-of-line
            switch:
                opening: new-line
            try:
                opening: end-of-line
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower
